# Generated by Django 2.1.8 on 2019-06-04 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('wielkosc_etatu', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'Etaty',
            },
        ),
        migrations.CreateModel(
            name='MiejscePracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('ST', 'Stacja Paliw'), ('BA', 'Baza Magazynowa')], default='ST', max_length=2)),
                ('nazwa', models.CharField(max_length=150)),
                ('ulica_nr', models.CharField(max_length=50)),
                ('miejscowosc', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=8)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Miejsca Pracy',
            },
        ),
        migrations.CreateModel(
            name='Nadzorca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Nadzorcy',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1)),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=40)),
                ('wzrost', models.PositiveSmallIntegerField()),
                ('kolnierzyk', models.PositiveSmallIntegerField()),
                ('szerokosc_w_pasie', models.PositiveSmallIntegerField()),
                ('rozmiar', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2)),
                ('nr_buta', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('opis', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.CreateModel(
            name='Kierownik',
            fields=[
                ('pracownik_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pracownicy.Pracownik')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kierownicy',
            },
            bases=('pracownicy.pracownik',),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='na_etacie', to='pracownicy.Etat'),
        ),
        migrations.AddField(
            model_name='etat',
            name='miejsce_pracy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracujacy_w_tym_miejscu', to='pracownicy.MiejscePracy'),
        ),
        migrations.AddField(
            model_name='etat',
            name='stanowisko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracujacy_na_tym_stanowisku', to='pracownicy.Stanowisko'),
        ),
    ]
