# Generated by Django 2.1.8 on 2019-05-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiejscePracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('ST', 'Stacja Paliw'), ('BA', 'Baza Magazynowa')], default='ST', max_length=2)),
            ],
        ),
    ]
