# Generated by Django 2.1.8 on 2019-05-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kierownik',
            name='created',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='kolnierzyk',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='nazwisko',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='nr_buta',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='plec',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='rozmiar',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='szerokosc_w_pasie',
        ),
        migrations.RemoveField(
            model_name='kierownik',
            name='wzrost',
        ),
        migrations.AddField(
            model_name='kierownik',
            name='pracownik_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pracownicy.Pracownik'),
            preserve_default=False,
        ),
    ]
