# Generated by Django 2.1.8 on 2019-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiejscePracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('ST', 'Stacja Paliw'), ('BA', 'Baza Magazynowa')], default='ST', max_length=2)),
                ('nazwa', models.CharField(max_length=150)),
                ('ul_i_nr', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=8)),
                ('miejscowosc', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
