# Generated by Django 2.1.8 on 2019-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0002_miejscepracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_stanowiska', models.CharField(choices=[('SPRZ', 'Sprzedawca'), ('PODJ', 'Podjazdowy'), ('KIER', 'Kierownik')], default='SPRZ', max_length=2)),
                ('czasokres_wymiany', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
