# Generated by Django 2.1.8 on 2019-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0003_stanowisko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='czasokres_wymiany',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
