# Generated by Django 2.1.8 on 2019-05-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0004_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1)),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=40)),
                ('wzrost', models.PositiveSmallIntegerField()),
                ('kolnierzyk', models.PositiveSmallIntegerField()),
                ('szerokosc_w_pasie', models.PositiveSmallIntegerField()),
                ('rozmiar', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2)),
                ('nr_buta', models.PositiveSmallIntegerField()),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracownicy', to='pracownicy.Etat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
