# Generated by Django 2.1.8 on 2019-07-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('during_composing', models.BooleanField(default=True)),
                ('composed', models.BooleanField(default=False)),
                ('sent_to_supervisor', models.BooleanField(default=False)),
                ('date_of_sending_to_supervisor', models.DateField(blank=True, null=True)),
                ('approved_by_supervisor', models.BooleanField(default=False)),
                ('sent_to_manufacturer', models.BooleanField(default=False)),
                ('date_of_sending_to_manufacturer', models.DateField(blank=True, null=True)),
                ('received_from_manufacturer', models.BooleanField(default=False)),
                ('date_of_receiving_from_manufacturer', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Manager')),
                ('place_of_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.WorkPlace')),
            ],
            options={
                'verbose_name_plural': 'Zamówienia',
            },
        ),
    ]
