# Generated by Django 2.1.8 on 2019-10-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved_by_supervisor',
            field=models.BooleanField(default=False, verbose_name='approved_by_supervisor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='composed',
            field=models.BooleanField(default=False, verbose_name='composed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_receiving_from_manufacturer',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_receiving_from_manufacturer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_sending_to_manufacturer',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_sending_to_manufacturer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_sending_to_supervisor',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_sending_to_supervisor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='during_composing',
            field=models.BooleanField(default=True, verbose_name='during_composing'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Manager', verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='order',
            name='place_of_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.WorkPlace', verbose_name='place_of_delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_from_manufacturer',
            field=models.BooleanField(default=False, verbose_name='received_from_manufacturer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_to_manufacturer',
            field=models.BooleanField(default=False, verbose_name='sent_to_manufacturer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_to_supervisor',
            field=models.BooleanField(default=False, verbose_name='sent_to_supervisor'),
        ),
    ]
