# Generated by Django 2.1.8 on 2019-12-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191029_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zamówienia', 'verbose_name_plural': 'Zamówienia'},
        ),
    ]
