# Generated by Django 2.1.8 on 2019-05-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pracownicy', '0002_auto_20190528_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodzajUbrania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150, unique=True)),
                ('opis', models.CharField(blank=True, max_length=300)),
                ('czasokres_wymiany', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubranie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zamowione', models.DateField(blank=True)),
                ('otrzymane', models.DateField(blank=True)),
                ('posiadane', models.DateField(blank=True)),
                ('zniszczone', models.DateField(blank=True)),
                ('pracownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubrania', to='pracownicy.Pracownik')),
                ('ubranie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubrania.RodzajUbrania')),
            ],
        ),
    ]
