# Generated by Django 2.1.8 on 2019-06-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pracownicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodzajUbrania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150, unique=True)),
                ('opis', models.CharField(blank=True, max_length=300)),
                ('czasokres_wymiany', models.PositiveSmallIntegerField()),
                ('przysluguje', models.ManyToManyField(to='pracownicy.Stanowisko')),
            ],
            options={
                'verbose_name_plural': 'Rodzaje ubrań',
            },
        ),
        migrations.CreateModel(
            name='Ubranie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zamowione', models.DateField(blank=True)),
                ('otrzymane', models.DateField(blank=True, null=True)),
                ('posiadane', models.DateField(blank=True, null=True)),
                ('zniszczone', models.DateField(blank=True, null=True)),
                ('pracownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubrania', to='pracownicy.Pracownik')),
                ('ubranie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wybrane', to='ubrania.RodzajUbrania')),
            ],
            options={
                'verbose_name_plural': 'Ubrania pracowników',
            },
        ),
    ]
