# Generated by Django 2.1.8 on 2019-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubrania', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodzajubrania',
            options={'verbose_name_plural': 'Rodzaje ubrań'},
        ),
        migrations.AlterModelOptions(
            name='ubranie',
            options={'verbose_name_plural': 'Ubrania pracowników'},
        ),
        migrations.AlterField(
            model_name='ubranie',
            name='otrzymane',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubranie',
            name='posiadane',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubranie',
            name='zniszczone',
            field=models.DateField(blank=True, null=True),
        ),
    ]
