# Generated by Django 2.1.8 on 2019-06-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubrania', '0002_auto_20190605_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubranie',
            old_name='ubranie',
            new_name='rodzaj',
        ),
    ]
