# Generated by Django 2.1.8 on 2019-06-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubrania', '0003_auto_20190608_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubranie',
            options={'ordering': ['zamowione'], 'verbose_name_plural': 'Ubrania pracowników'},
        ),
    ]
