# Generated by Django 2.1.8 on 2019-06-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubrania', '0004_auto_20190620_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubranie',
            options={'ordering': ['-zamowione'], 'verbose_name_plural': 'Ubrania pracowników'},
        ),
    ]
