# Generated by Django 2.1.8 on 2019-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.DateField(blank=True)),
                ('received', models.DateField(blank=True, null=True)),
                ('owned', models.DateField(blank=True, null=True)),
                ('destroyed', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ubrania pracowników',
                'ordering': ['-ordered'],
            },
        ),
        migrations.CreateModel(
            name='KindOfClothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('time_to_exchange', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Rodzaje ubrań',
            },
        ),
    ]
