# Generated by Django 2.1.8 on 2019-07-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20190711_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='prepared_to_order',
            field=models.BooleanField(default=False),
        ),
    ]
