# Generated by Django 2.1.8 on 2019-07-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindofclothe',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clothes.Manufacturer'),
            preserve_default=False,
        ),
    ]
