# Generated by Django 2.1.8 on 2019-07-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_kindofclothe_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name_plural': 'Producenci'},
        ),
    ]
