# Generated by Django 2.1.8 on 2019-07-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_auto_20190722_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
