# Generated by Django 2.1.8 on 2019-07-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_clothe_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothe',
            old_name='delivered',
            new_name='delivered_ok',
        ),
    ]
