# Generated by Django 2.1.8 on 2019-07-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_auto_20190727_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='delivered_with_defects',
            field=models.BooleanField(default=False),
        ),
    ]
