# Generated by Django 2.1.8 on 2019-07-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_clothe_not_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
