# Generated by Django 2.1.8 on 2019-10-29 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_clothe_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='employees.Employee', verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='clothes.KindOfClothe', verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_ordered', to='orders.Order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='available_for',
            field=models.ManyToManyField(to='employees.Position', verbose_name='available_for'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='months_to_exchange',
            field=models.PositiveSmallIntegerField(verbose_name='months_to_exchange'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name of Manufacturer'),
        ),
    ]
