# Generated by Django 2.1.8 on 2019-11-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_auto_20191030_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Producent', 'verbose_name_plural': 'Producenci'},
        ),
    ]
