# Generated by Django 2.1.8 on 2019-12-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0017_auto_20191108_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothe',
            options={'ordering': ['-ordered'], 'verbose_name': 'Ubranie', 'verbose_name_plural': 'Ubrania pracowników'},
        ),
        migrations.AlterModelOptions(
            name='kindofclothe',
            options={'verbose_name': 'Rodzaj Ubrania', 'verbose_name_plural': 'Rodzaje ubrań'},
        ),
    ]
