# Generated by Django 2.1.8 on 2019-12-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0019_auto_20191204_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='employees.Employee', verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='clothes.KindOfClothe', verbose_name='Rodzaj'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_in_order', to='orders.Order', verbose_name='Zamówienie'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='available_for',
            field=models.ManyToManyField(to='employees.Position', verbose_name='Dostęopne dla'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Manufacturer', verbose_name='Producent'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='months_to_exchange',
            field=models.PositiveSmallIntegerField(verbose_name='Czasokres wymiany w miesiącach'),
        ),
        migrations.AlterField(
            model_name='kindofclothe',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nazwa'),
        ),
    ]
