# Generated by Django 2.1.8 on 2019-07-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sex', models.CharField(choices=[('W', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=40)),
                ('height', models.PositiveSmallIntegerField()),
                ('colar', models.PositiveSmallIntegerField()),
                ('width_waist', models.PositiveSmallIntegerField()),
                ('body_size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2)),
                ('shoe_size', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('size_of_job', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'Etaty',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Nadzorcy',
            },
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('ST', 'Stacja Paliw'), ('BA', 'Baza Magazynowa')], default='ST', max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Miejsca Pracy',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.Employee')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Kierownicy',
            },
            bases=('employees.employee',),
        ),
    ]
