# Generated by Django 2.1.8 on 2019-11-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_job_size_of_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_position', to='employees.Position', verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='position_2',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_position', to='employees.Position', verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='size_of_position_1',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=3, verbose_name='size_of_job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='size_of_position_2',
            field=models.DecimalField(blank=True, decimal_places=2, default='1', max_digits=3, verbose_name='size_of_job'),
            preserve_default=False,
        ),
    ]
