# Generated by Django 2.1.8 on 2019-11-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20191125_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='description'),
        ),
    ]
