# Generated by Django 2.1.8 on 2019-11-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20191126_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='work_place',
        ),
    ]
