# Generated by Django 2.1.8 on 2019-11-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_work_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='work_place',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='employees.WorkPlace', verbose_name='work_place'),
            preserve_default=False,
        ),
    ]
