# Generated by Django 2.1.8 on 2019-11-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_manager_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=15, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('W', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1, verbose_name='płeć'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=40, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=15, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='sex',
            field=models.CharField(choices=[('W', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1, verbose_name='płeć'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='surname',
            field=models.CharField(max_length=40, verbose_name='nazwisko'),
        ),
    ]
