# Generated by Django 2.1.8 on 2019-11-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20191126_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='body_size',
            field=models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2, verbose_name='rozmiar'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='colar',
            field=models.PositiveSmallIntegerField(verbose_name='kołnierzyk'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='height',
            field=models.PositiveSmallIntegerField(verbose_name='wzrost'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shoe_size',
            field=models.PositiveSmallIntegerField(verbose_name='nr buta'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='width_waist',
            field=models.PositiveSmallIntegerField(verbose_name='szerokość w pasie'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='body_size',
            field=models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2, verbose_name='rozmiar'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='colar',
            field=models.PositiveSmallIntegerField(verbose_name='kołnierzyk'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='height',
            field=models.PositiveSmallIntegerField(verbose_name='wzrost'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='shoe_size',
            field=models.PositiveSmallIntegerField(verbose_name='nr buta'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='width_waist',
            field=models.PositiveSmallIntegerField(verbose_name='szerokość w pasie'),
        ),
    ]
