# Generated by Django 2.1.8 on 2019-12-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20191204_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Imię i Nazwisko'),
        ),
    ]
