# Generated by Django 2.1.8 on 2019-12-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_auto_20191204_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Pracownik', 'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Etat', 'verbose_name_plural': 'Etaty'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Kierownik', 'verbose_name_plural': 'Kierownicy'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Stanowisko', 'verbose_name_plural': 'Stanowiska'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'Nadzorca', 'verbose_name_plural': 'Nadzorcy'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'Miejsce Pracy', 'verbose_name_plural': 'Miejsca Pracy'},
        ),
    ]
