# Generated by Django 2.1.8 on 2019-06-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubrania', '0001_initial'),
        ('pracownicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateField()),
                ('data_zatwierdzenia', models.DateField(blank=True, null=True)),
                ('data_wyslania', models.DateField(blank=True, null=True)),
                ('data_otrzymania', models.DateField(blank=True, null=True)),
                ('miejsce_dostawy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamawiane_ubrania', to='pracownicy.MiejscePracy')),
                ('ubranie_zamawiane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zlozone_zamowienia', to='ubrania.Ubranie')),
                ('zamawiajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamawiajacy', to='pracownicy.Kierownik')),
            ],
            options={
                'verbose_name_plural': 'Zamówienia',
            },
        ),
    ]
